#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'apt'
cookbook 'build-essential'
cookbook 'user', :git => 'https://github.com/fnichol/chef-user.git'
cookbook 'ufw', :git => 'https://github.com/opscode-cookbooks/ufw.git'
cookbook 'application_ruby', :git => 'https://github.com/opscode-cookbooks/application_ruby'
cookbook 'sqlite'
cookbook 'unattended-upgrades', :git => 'https://github.com/firstbanco/chef-unattended-upgrades.git'
cookbook 'rvm', :git => 'https://github.com/fnichol/chef-rvm'
cookbook 'postgresql', :git => 'https://github.com/phlipper/chef-postgresql'
