#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


cookbook 'apt', :git => 'https://github.com/opscode-cookbooks/apt.git'
cookbook 'runit', :git => 'https://github.com/opscode-cookbooks/runit.git'
cookbook 'build-essential'
cookbook 'user', :git => 'https://github.com/fnichol/chef-user.git'
cookbook 'ufw', :git => 'https://github.com/opscode-cookbooks/ufw.git'
cookbook 'application_ruby', :git => 'https://github.com/opscode-cookbooks/application_ruby'
cookbook 'sqlite'
cookbook 'unattended-upgrades', :git => 'https://github.com/firstbanco/chef-unattended-upgrades.git'
cookbook 'rbenv', :git => 'https://github.com/fnichol/chef-rbenv'
cookbook 'ruby_build', :git => 'https://github.com/fnichol/chef-ruby_build.git'
cookbook 'postgresql', :git => 'https://github.com/phlipper/chef-postgresql'
